name: Deploy Library

on:
  push:
    tags:
      - 'v*.*.*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write

    steps:
      
      # Переходим на нужную ветку
      - uses: actions/checkout@v4

      # Настраиваем java окружение
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'
          cache: 'gradle'

      # Даём права на выполнение gradle
      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      #      - name: Run tests
      #        run: |
      #          ./gradlew test


      # Генерируем APK
      - name: Publish Lib to Github Packages and Maven Central
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
          SIGNING_SECRET_KEY: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: |
          ./gradlew publishToCentralPortal --debug
