name: Deploy Library

on:
  push:
    tags:
      - 'v*.*.*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write
      packages: write

    steps:

      # Настройка переменных
      - name: Set up environment variables
        run: |
          echo "release_path=${{ github.workspace }}/ogson_${{ github.ref_name }}_$(date +'%Y-%m-%d').zip" >> $GITHUB_ENV
      
      # Переходим на нужную ветку
      - uses: actions/checkout@v4

      # Настраиваем java окружение
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # Публикуем библиотеку в maven central
      - name: Publish library Github Packages and Maven Central
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
          SIGNING_SECRET_KEY: ${{ secrets.SIGNING_SECRET_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: |
          ./gradlew publishToCentralPortal

      - name: Rename archive for release
        run: |
          cp $GITHUB_WORKSPACE/build/local_maven/bundle.zip ${{ env.release_path }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            ${{ env.release_path }}
